### ISSUE TITLE
Real position in camera space

### ISSUE THREAD

**Issue by xiaoyudanaa** [yw0208/W-HMR#1]
Excellent work. Does this approach accurately provide the actual 3D positions of the SMPL model? For instance, methods like 4D-humans and Pymaf are known to be imprecise in outputting depth information. Could you recommend an advanced approach for achieving real position 3D human reconstruction utilizing monocular video footage? Your expertise and insights on this matter would be immensely appreciated.

**Comment by yw0208** [comment]
Thanks for your question. W-HMR is more concerned with pose correction in world space and mesh-image alignment for precise training. You can check out the following works https://liuyebin.com/proxycap/, https://github.com/vye16/slahmr and https://github.com/IDEA-Research/Motion-X. They may help you.

**Comment by xiaoyudanaa** [comment]
非常感谢您的回复。我面临的一个难题是：重建具有真实绝对位置的SMPL，而不是相对位置。您提到的slahmr--它是通过优化的方式来解耦相机，虽然可以获取人体的真实绝对位置，但此类后优化的方法，无法修改为实时的方案。而我想要一个能够实时运行的捕获真实绝对位置的人体重建方法，目前想到的是通过身高进行简单的后优化，但这过于简单。您方便的话，我想加您的微信，向您请教一下，我将不胜感激，我的微信是：Weafree
