### ISSUE TITLE
ViTPose incorrect path

### ISSUE THREAD

**Issue by blockinhead** [yw0208/W-HMR#4]
Hi
Something wrong with import path: [here](https://github.com/yw0208/W-HMR/blob/a83d55f24e2c4844bf97b11ff179f02b3aca2bcf/models/pose_vit.py#L5) you import from `models.ViTPose` with capital T, but the corresponding path in the project is with small t. As [below](https://github.com/yw0208/W-HMR/blob/a83d55f24e2c4844bf97b11ff179f02b3aca2bcf/models/pose_vit.py#L18) the path to a file is with capital T too, I think just renaming `VitPose` to `ViTPose` will resolve the issue.

**Comment by yw0208** [comment]
Wow, I made a mistake. Thank you so much. You are right; I have fixed the bug as your suggestions.
