### ISSUE TITLE
some absolute paths to ckpt files

### ISSUE THREAD

**Issue by blockinhead** [yw0208/W-HMR#5]
there are 5 checkpoints in the project, that are loaded by an absolute path:  
[this](https://github.com/yw0208/W-HMR/blob/a83d55f24e2c4844bf97b11ff179f02b3aca2bcf/models/pose_vit.py#L21
) vitpose checkpoint, [this](https://github.com/yw0208/W-HMR/blob/a83d55f24e2c4844bf97b11ff179f02b3aca2bcf/models/whmr.py#L72) smpl model, [this](https://github.com/yw0208/W-HMR/blob/a83d55f24e2c4844bf97b11ff179f02b3aca2bcf/models/whmr.py#L77) pymaf checkpoint, [this](https://github.com/yw0208/W-HMR/blob/a83d55f24e2c4844bf97b11ff179f02b3aca2bcf/models/whmr.py#L437) very important place and [this](https://github.com/yw0208/W-HMR/blob/a83d55f24e2c4844bf97b11ff179f02b3aca2bcf/models/VitPose/scratch/test.py#L8) not so important place.

**Comment by yw0208** [comment]
Thanks for your reminder. I've changed the path to relative paths. The missing files have been added to the download resources.

**Comment by blockinhead** [comment]
thanks, now everything seems to be in place
