### ISSUE TITLE
ratio of training dataset

### ISSUE THREAD

**Issue by YangChangHee** [yw0208/W-HMR#6]
hello,
What is the approximate ratio among training datasets?
Ex) Human 3.6m 0.2, 3DPW 0.05, MPII3D 0.05, MPII 0.05, AGORA 0.2, COCO 0.15, SPEC-SYN 0.1 , and HuMMan 0.2. 
thank you great work!

**Comment by yw0208** [comment]
Hi, the ratio should be
h36m: 0.4
humman: 0.1
MPII3D: 0.1
COCO: 0.1
AGORA+SPEC-SYN: 0.2
Others(e.g. lsp, 3dpw) ：0.1
There are better ratios than this, and they can be adjusted appropriately according to your needs.

**Comment by YangChangHee** [comment]
Thank you for your quick reply :)
