### ISSUE TITLE
for video ?

### ISSUE THREAD

**Issue by luoww1992** [yw0208/W-HMR#8]

**Comment by yw0208** [comment]
For video?
If you want to get recovery results from a video, you can run the command:
```
ffmpeg -i input_video.mp4 -r 1 output_image_%03d.png
```
Then you can get a sequence of images and use my demo code.

If you want to turn the demo images to a video, just run the command:
```
ffmpeg -framerate 30 -i image%03d.png -c:v libx264 -profile:v high -crf 20 -pix_fmt yuv420p output_video.mp4
```
Specific parameters can be set according to your needs.
